# Generated by Django 3.1.2 on 2023-03-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField()),
                ('duration', models.DurationField(null=True)),
                ('check_out_time', models.TimeField()),
                ('resort', models.CharField(max_length=64)),
                ('adven_sub_category', models.CharField(max_length=64)),
                ('regular_fare', models.FloatField(null=True)),
                ('premium_fare', models.FloatField(null=True)),
                ('checkin_day', models.ManyToManyField(related_name='checkin_day', to='flight.Week')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='flight.places')),
            ],
        ),
    ]
