# Generated by Django 3.1.2 on 2023-03-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_booking_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='adven_place',
        ),
    ]
