# Generated by Django 3.1.2 on 2023-03-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20230327_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='origin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='flight.adven_place'),
        ),
    ]
