# Generated by Django 3.1.2 on 2023-03-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_booking_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adven_sub_category',
            new_name='adven',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='checkin_day',
            new_name='check_in_day',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in_time',
            new_name='check_in_timing',
        ),
    ]
