# Generated by Django 3.1.2 on 2023-03-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_auto_20230327_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='adven_booking',
        ),
    ]
