# Generated by Django 3.1.2 on 2023-03-28 06:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20230327_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='adven_Ticket_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=6, unique=True)),
                ('adven_ddate', models.DateField(blank=True, null=True)),
                ('adve_adate', models.DateField(blank=True, null=True)),
                ('adven_fare', models.FloatField(blank=True, null=True)),
                ('other_charges', models.FloatField(blank=True, null=True)),
                ('total_fare', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'Usd'), ('CAD', 'Cad')], max_length=20)),
                ('service_class', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium')], max_length=20)),
                ('booking_date', models.DateTimeField(default=datetime.datetime.now)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=45)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], max_length=45)),
                ('adven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_adven_tickets', to='flight.adven_booking')),
                ('passengers', models.ManyToManyField(related_name='user_flight_tickets', to='flight.Passenger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
