# Generated by Django 3.1.2 on 2023-04-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_adven_ticket_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
